Repository nasa/tblCRCTool, pull requests merged in 2021-02, with the labels that each got.

#24 Fix #19, Change full word help option '-help' to '--help'
  cfe_ts_crc.c
Labels: CCB:2021-02-02, CCB:FastTrack, IC:2021-02-02, community

#32 Fix #31, Add static analysis and format check
  .github/workflows/format-check.yml
  .github/workflows/static-analysis.yml
  README.md
  cfe_ts_crc_version.h
Labels: CCB:FastTrack, IC:2021-02-02, continuous-integration

#34 Fix #33, Add CodeQL analysis to workflow
  .github/workflows/codeql-build.yml
Labels: CCB:FastTrack, continuous-integration

#35 tblCRCTool Integration candidate: 2021-02-02
  .github/workflows/codeql-build.yml
  .github/workflows/format-check.yml
  .github/workflows/static-analysis.yml
  README.md
  cfe_ts_crc.c
  cfe_ts_crc_version.h
Labels: IC:2021-02-02
