Repository nasa/tblCRCTool, pull requests merged in 2021-01, with the labels that each got.

#28 Fix #27, Create Security Policy
  SECURITY.md
Labels: CCB:FastTrack, IC:2021-01-19, docs, security

#26 Fix #15, Remove unimplemented crc cases
  cfe_ts_crc.c
Labels: CCB:FastTrack, IC:2021-01-19

#30 Fix #20, Replace LRO reference with algorithm details
  cfe_ts_crc.c
Labels: CCB-READY, CCB:FastTrack, IC:2021-01-19
